# Generated by Django 4.2.21 on 2025-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionsearch',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
