# Generated by Django 4.2.21 on 2025-05-29 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
