# Generated by Django 4.2.21 on 2025-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0002_alter_connectionsearch_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsearch',
            name='reset',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
