# Generated by Django 4.2.21 on 2025-05-31 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swipe', '0002_connectionsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsearch',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectionsearch',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionsearch',
            name='interest_filter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_search', to=settings.AUTH_USER_MODEL),
        ),
    ]
