# Generated by Django 4.2.21 on 2025-06-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0003_connectionsearch_reset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionsearch',
            old_name='reset',
            new_name='lock',
        ),
    ]
