# Generated by Django 4.2.21 on 2025-05-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dater',
            name='username',
        ),
        migrations.AlterField(
            model_name='dater',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dater',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
