# Generated by Django 3.2.6 on 2025-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dater',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
