# Generated by Django 4.2.21 on 2025-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dater',
            name='interests',
            field=models.CharField(blank=True, choices=[('singing', 'Singing'), ('travelling', 'Travelling'), ('gaming', 'Gaming'), ('photography', 'Photography'), ('gardening', 'Gardening')], max_length=200, null=True),
        ),
    ]
