# Generated by Django 3.2.6 on 2025-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_dater_profile_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='dater',
            name='profile_completed',
        ),
        migrations.AddField(
            model_name='dater',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dater',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dater',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='dater',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='dater',
            name='first_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='dater',
            name='last_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
