# Generated by Django 4.2.21 on 2025-06-01 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_dater_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilesHasOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
