# Generated by Django 4.2.21 on 2025-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profileshasotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dater',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10),
        ),
    ]
