# Generated by Django 3.2.6 on 2025-05-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20250506_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dater',
            name='bio',
        ),
    ]
