# Generated by Django 4.2.21 on 2025-05-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_dater_first_name_alter_dater_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dater',
            managers=[
            ],
        ),
    ]
