# Generated by Django 4.2.21 on 2025-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_dater_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dater',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
