# Generated by Django 4.2.21 on 2025-06-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_dater_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dater',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='dater',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='dater',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
