# Generated by Django 4.2.21 on 2025-06-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_dater_photo2_dater_photo3_dater_photo4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dater',
            old_name='photo',
            new_name='mandetory_image',
        ),
        migrations.RenameField(
            model_name='dater',
            old_name='photo2',
            new_name='optional_image1',
        ),
        migrations.RenameField(
            model_name='dater',
            old_name='photo3',
            new_name='optional_image2',
        ),
        migrations.RenameField(
            model_name='dater',
            old_name='photo4',
            new_name='optional_image3',
        ),
    ]
