# Generated by Django 4.2.21 on 2025-06-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_photo_dater_mandetory_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dater',
            old_name='mandetory_image',
            new_name='mandatory_image',
        ),
    ]
