# Generated by Django 4.2.21 on 2025-06-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_dater_mandatory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dater',
            name='mandatory_image',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
