# Generated by Django 4.2.21 on 2025-06-17 19:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_dater_mandatory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dater',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('singing', 'Singing'), ('travelling', 'Travelling'), ('gaming', 'Gaming'), ('photography', 'Photography'), ('gardening', 'Gardening')], max_length=47, null=True),
        ),
    ]
