# Generated by Django 3.2.6 on 2025-05-05 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HopingFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('hobby', 'Hobby'), ('music', 'Music Genre'), ('sport', 'Sport'), ('language', 'Language'), ('pet', 'Pet Preference')], max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('lifestyle', models.CharField(blank=True, choices=[('drinking', 'Drinking'), ('smoking', 'Smoking'), ('have_kids', 'Have Kids'), ('want_kids', 'Want Kids'), ('religion', 'Religion'), ('political_views', 'Political Views'), ('causes', 'Causes & Communities')], max_length=20, null=True)),
                ('height', models.CharField(blank=True, choices=[('4_0', "4'0"), ('4_1', "4'1"), ('7_0', "7'0")], max_length=4, null=True)),
                ('relationship_goal', models.CharField(blank=True, choices=[('dating', 'Dating'), ('bff', 'BFF')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choice', models.CharField(choices=[('kindness', 'Kindness'), ('humor', 'Humor'), ('honesty', 'Honesty')], max_length=20)),
            ],
            options={
                'verbose_name': 'Quality',
                'verbose_name_plural': 'Qualities',
            },
        ),
        migrations.CreateModel(
            name='UserQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilequality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
            options={
                'unique_together': {('user', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.interestcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'interest')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='hoping_for',
            field=models.ManyToManyField(related_name='hoping_profiles', through='user_profile.HopingFor', to='user_profile.ProfileQuality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='profiles', through='user_profile.UserInterest', to='user_profile.InterestCategory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualities',
            field=models.ManyToManyField(related_name='profiles', through='user_profile.UserQuality', to='user_profile.ProfileQuality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hopingfor',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilequality'),
        ),
        migrations.AddField(
            model_name='hopingfor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='hopingfor',
            unique_together={('user', 'quality')},
        ),
    ]
