# Generated by Django 3.2.6 on 2025-05-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interestcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hoping_for',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qualities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userquality',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userquality',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='userquality',
            name='user',
        ),
        migrations.DeleteModel(
            name='HopingFor',
        ),
        migrations.DeleteModel(
            name='InterestCategory',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileQuality',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
        migrations.DeleteModel(
            name='UserQuality',
        ),
    ]
