# Generated by Django 4.2.21 on 2025-05-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_profile_daterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
